"""Splunk MCP client — connects to Splunkbase App #7931 over Streamable HTTP.

The Splunk MCP Server App (https://splunkbase.splunk.com/app/7931) exposes
Splunk's search, index, and saved-search APIs as MCP tools. This module is
a thin wrapper around the official `mcp` Python SDK that handles the two
non-obvious pieces:

1. **Transport**: the App uses the modern MCP Streamable HTTP transport
   (per the MCP 2025-06-18 spec), *not* the older SSE transport — so you
   need `mcp.client.streamable_http.streamablehttp_client`, not
   `mcp.client.sse.sse_client`. Hitting the SSE client gets you HTTP 405.

2. **Auth + self-signed TLS**: Splunk dev instances run on self-signed
   certs by default. We wire a custom `httpx_client_factory` into the
   MCP client so `verify_ssl=False` actually takes effect (which it
   doesn't if you just construct an `ssl.SSLContext` standalone — the
   MCP SDK won't pick it up). Auth header is `Authorization: Splunk
   <encrypted-token>`; the encrypted token is generated by POSTing to
   `/services/mcp_token?username=<user>&action=rotate` then GET-ing
   `?action=get` on the same endpoint.
"""
from __future__ import annotations

import logging
from typing import Any

import httpx

try:
    from mcp import ClientSession
    from mcp.client.streamable_http import streamablehttp_client
    from mcp.types import Tool as MCPTool
    _MCP_AVAILABLE = True
except ImportError:
    _MCP_AVAILABLE = False
    ClientSession = None  # type: ignore[assignment,misc]
    streamablehttp_client = None  # type: ignore[assignment]
    MCPTool = None  # type: ignore[assignment,misc]

logger = logging.getLogger(__name__)


class SplunkMCPClient:
    """Async context manager that connects to the Splunk MCP Server.

    Usage:

        async with SplunkMCPClient(splunk_token="...", verify_ssl=False) as c:
            tools = await c.list_tools()                # raw MCP tools
            out = await c.call_tool("splunk_run_query",
                                    {"query": "search index=_internal | head 5"})
    """

    def __init__(
        self,
        splunk_token: str,
        splunk_url: str = "https://localhost:8089/services/mcp",
        verify_ssl: bool = True,
    ) -> None:
        if not _MCP_AVAILABLE:
            raise RuntimeError(
                "The 'mcp' Python package is not installed. "
                "Install: pip install splunkguard-mcp  (mcp is a hard dep)."
            )
        self._splunk_token = splunk_token
        self._splunk_url = splunk_url.rstrip("/")
        self._verify_ssl = verify_ssl
        self._session: ClientSession | None = None
        self._transport_cm = None

    @staticmethod
    def mcp_available() -> bool:
        """True iff the `mcp` Python package is importable."""
        return _MCP_AVAILABLE

    async def is_reachable(self) -> bool:
        """Quick HTTP probe of the Splunk MCP endpoint (HEAD-safe)."""
        try:
            async with httpx.AsyncClient(verify=self._verify_ssl, timeout=5.0) as client:
                r = await client.get(
                    self._splunk_url,
                    headers={"Authorization": f"Splunk {self._splunk_token}"},
                )
                # 405 Method Not Allowed = endpoint exists, expects POST
                return r.status_code < 500
        except Exception as exc:
            logger.debug("Splunk MCP reachability probe failed: %s", exc)
            return False

    async def __aenter__(self) -> "SplunkMCPClient":
        headers = {
            "Authorization": f"Splunk {self._splunk_token}",
            "Content-Type": "application/json",
        }

        verify_ssl = self._verify_ssl

        def _httpx_factory(
            headers: dict[str, str] | None = None,
            timeout: httpx.Timeout | None = None,
            auth: httpx.Auth | None = None,
        ) -> httpx.AsyncClient:
            return httpx.AsyncClient(
                verify=verify_ssl,
                headers=headers,
                timeout=timeout if timeout is not None else httpx.Timeout(30.0),
                auth=auth,
                follow_redirects=True,
            )

        logger.info("Connecting to Splunk MCP Server at %s …", self._splunk_url)
        self._transport_cm = streamablehttp_client(
            url=self._splunk_url,
            headers=headers,
            httpx_client_factory=_httpx_factory,
        )
        # streamablehttp_client yields (read, write, get_session_id_callback)
        read, write, _get_session_id = await self._transport_cm.__aenter__()
        self._session = ClientSession(read, write)
        await self._session.__aenter__()
        await self._session.initialize()
        logger.debug("Splunk MCP Server session ready")
        return self

    async def __aexit__(self, *exc_info: Any) -> None:
        if self._session:
            await self._session.__aexit__(*exc_info)
        if self._transport_cm:
            await self._transport_cm.__aexit__(*exc_info)

    async def list_tools(self) -> list[MCPTool]:
        """Return the raw MCP tool list as advertised by Splunk."""
        assert self._session is not None
        result = await self._session.list_tools()
        logger.debug("Loaded %d tools from Splunk MCP Server", len(result.tools))
        return list(result.tools)

    async def call_tool(self, name: str, arguments: dict[str, Any]) -> str:
        """Execute a Splunk MCP tool by name; return its text output joined."""
        assert self._session is not None
        result = await self._session.call_tool(name, arguments)
        if result.isError:
            logger.warning("Splunk MCP tool %r returned an error", name)
        parts: list[str] = []
        for item in result.content:
            if hasattr(item, "text"):
                parts.append(item.text)
            else:
                parts.append(str(item))
        return "\n".join(parts)
